name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Always install Poetry with Python 3.9+
    - name: Set up Python for Poetry
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install Poetry
      uses: abatilo/actions-poetry@v4

    # Set up the Python version for the test environment
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: poetry install --extras aibom

    - name: Install extra test dependencies
      run: poetry run pip install boto3 google-auth

    - name: Run tests
      run: poetry run pytest
